Check latest tag is release tag in bump version workflow

diff --git a/.github/workflows/bump-release-version.yml b/.github/workflows/bump-release-version.yml
--- a/.github/workflows/bump-release-version.yml
+++ b/.github/workflows/bump-release-version.yml
@@ -93,10 +93,7 @@ jobs:
 
         # Check if the latest tag is the ossm tag (meaning no release tag of current version exists)
         LATEST_TAG=$(git describe --tags --abbrev=0)
-        if [[ "$LATEST_TAG" == "$RAW_VERSION-ossm" ]]; then
-          echo "Error: Cannot bump release version because the latest tag is not the release tag $RAW_VERSION"
-          exit 1
-        else
+        if [[ "$LATEST_TAG" == "$RAW_VERSION" ]]; then
           RELEASE_VERSION=$(python bump.py patch $RAW_VERSION)
 
           # Update the version in Kiali repository
@@ -110,4 +107,7 @@ jobs:
 
           # Create the ossm version tag
           git push origin $(git rev-parse HEAD):refs/tags/$RELEASE_VERSION-ossm
+        else
+          echo "Error: Cannot bump to the next version because the release tag $RAW_VERSION is not the latest tag"
+          exit 1
         fi
